services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: orion_postgres

    environment:
      POSTGRES_USER: orion
      POSTGRES_PASSWORD: orion_dev_pass
      POSTGRES_DB: orion_dev

    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
